@startuml
' Roll your own theme: https://bschwarz.github.io/puml-themes/rolling.html
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/materia-outline/puml-theme-materia-outline.puml
title "Vitrina at-a-glance"

' autonumber

actor Developer

Developer -> Terminal : Run Vitrina --host
Terminal -> Vitrina : pypr install...
Vitrina -> Host : provision services

activate Host
Host --> Vitrina : Ready
Vitrina -> Host : Test features
Host --> Vitrina : Results
Vitrina -> Host : HTML reports
Vitrina -> Terminal : View reports at http...
deactivate

group  Share the Portfolio
boundary Browser
actor Reviewer
    Reviewer -> Browser : Open reports
    activate Browser
    Browser -> Host : Get HTML reports
    Host -> Browser : HTML reports
    Browser -> Reviewer : lovely HTML + Javascript
    deactivate
@enduml