@startuml
' !include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/sketchy-outline/puml-theme-sketchy-outline.puml
title "Lifecycle At-A-Glance"

actor Developer
boundary Terminal
'----------------------

group Using defaults
Developer -> Terminal : Run Vitrina -settings
Terminal -> Vitrina : start tests..
Vitrina -> Host : begin inspections
    activate Host
    Host -> Host : query infrastructure
    Host -> Host : write results
    Host --> Vitrina : Results of Tests

    activate Vitrina
    Vitrina -> Host : Formatted report
    deactivate Host

    Vitrina -> Terminal : Link to reports
    deactivate Vitrina
end group
'----------------------

group  Share the Portfolio
boundary Browser
actor Reviewer
    Reviewer -> Browser : Open reports
    activate Browser
    Browser -> Host : Get HTML reports
    Host -> Browser : HTML reports
    Browser -> Reviewer : lovely HTML + Javascript
    deactivate
end group
'----------------------

group Extending Vitrina

Developer -> Vitrina : describe feature
Developer  ->  Vitrina : define test step
Developer -> Host : implement feature

    activate Vitrina
    Vitrina -> Host : run steps
    Host --> Vitrina : results
    Vitrina -> Host : POST HTML reports
    Vitrina -> Terminal : view reports at http...
    deactivate Vitrina

end group

@enduml