@startuml
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/sketchy-outline/puml-theme-sketchy-outline.puml
title "Starting Vitrina"
actor Developer

Developer -> Terminal : Run Vitrina --host
Terminal -> Vitrina : pypr install...
Vitrina -> Host : provision services

activate Host
    Host --> Vitrina : Ready
    Vitrina -> Host : Test features
    Host --> Vitrina : Results
    Vitrina -> Host : HTML reports
deactivate
Vitrina -> Terminal : View reports at http...

@enduml